Repository DeveloperAcademy-POSTECH/MacC-Team5-COMBINE, pull requests merged in 2023-11, with the labels that each got.

#45 [Refactor] 호랑이 애니메이션 뷰 리팩토링
  Codingdong-iOS/Codingdong-iOS/Presentation/GiveTtekk/NoTtekkViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/TigerAnimation/VIewController/TigerAnimationViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/TigerAnimation/View/TigerLottieAnimationVIew.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Ttekkkochi/ViewController/TtekkkochiViewController.swift
Labels: ♻️ Refactor, 🍺 션

#41 [REFACTOR] 떡 주기 뷰 리팩토링
  Codingdong-iOS/Codingdong-iOS.xcodeproj/project.pbxproj
  Codingdong-iOS/Codingdong-iOS/Presentation/GiveTtekk/GiveTtekkViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/GiveTtekk/NoTtekkViewController.swift
Labels: ♻️ Refactor, 🚢 노아

#49 [Feat] 내책장 뷰 레이아웃 작업
  Codingdong-iOS/Codingdong-iOS.xcodeproj/project.pbxproj
  Codingdong-iOS/Codingdong-iOS/Model/BadgeList.swift
  Codingdong-iOS/Codingdong-iOS/Model/StoryTitle.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/GiveTtekk/GiveTtekkViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/MyBookShelf/View/BadgeCollectionView.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/MyBookShelf/View/BadgeCollectionViewCell.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/MyBookShelf/View/StoryListTableView.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/MyBookShelf/View/StoryListTableViewCell.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/MyBookShelf/ViewController/MyBookShelfViewController.swift
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/DummyBadgeA2.imageset/Contents.json
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/DummyBadgeA2.imageset/YugwaA2@2x.svg
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/DummyBadgeA4.imageset/Contents.json
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/DummyBadgeA4.imageset/YugwaA4@2x.svg
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/DummyBadgeB3.imageset/Contents.json
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/DummyBadgeB3.imageset/YugwaB3@2x.svg
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/DummyBadgeB5.imageset/Contents.json
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/DummyBadgeB5.imageset/YugwaB5@2x.svg
Labels: ⭐️ Feat, 🍺 션

#51 [SETTING] Log 파일 SPM을 통해 추가
  Codingdong-iOS/Codingdong-iOS.xcodeproj/project.pbxproj
  Codingdong-iOS/Codingdong-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Codingdong-iOS/Codingdong-iOS/Presentation/MyBookShelf/ViewController/MyBookShelfViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Ttekkkochi/ViewModel/TtekkkochiViewModel.swift
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Log.swift
Labels: ⚙️ Setting, 🍭 조이

#52 [DESIGN] 재사용할 수 있는 카드뷰 추가
  Codingdong-iOS/Codingdong-iOS/Presentation/Components/CardView.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Components/Constants.swift
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Learning Badge/Contents.json
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Learning Badge/learning_badge1.imageset/Contents.json
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Learning Badge/learning_badge1.imageset/concept3.png
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Learning Badge/learning_badge1.imageset/concept3@2x.png
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Learning Badge/learning_badge1.imageset/concept3@3x.png
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Learning Badge/learning_badge2.imageset/Contents.json
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Learning Badge/learning_badge2.imageset/concept4.png
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Learning Badge/learning_badge2.imageset/concept4@2x.png
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Learning Badge/learning_badge2.imageset/concept4@3x.png
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Learning Badge/learning_badge3.imageset/Contents.json
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Learning Badge/learning_badge3.imageset/concept5.png
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Learning Badge/learning_badge3.imageset/concept5@2x.png
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Learning Badge/learning_badge3.imageset/concept5@3x.png
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/The Sun and the Moon/Contents.json
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/The Sun and the Moon/sm_concept1.imageset/Contents.json
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/The Sun and the Moon/sm_concept1.imageset/concept1.png
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/The Sun and the Moon/sm_concept1.imageset/concept1@2x.png
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/The Sun and the Moon/sm_concept1.imageset/concept1@3x.png
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/The Sun and the Moon/sm_concept2.imageset/Contents.json
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/The Sun and the Moon/sm_concept2.imageset/sm_concept2.png
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/The Sun and the Moon/sm_concept2.imageset/sm_concept2@2x.png
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/The Sun and the Moon/sm_concept2.imageset/sm_concept2@3x.png
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/The Sun and the Moon/sm_concept3.imageset/Contents.json
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/The Sun and the Moon/sm_concept3.imageset/concept2.png
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/The Sun and the Moon/sm_concept3.imageset/concept2@2x.png
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/The Sun and the Moon/sm_concept3.imageset/concept2@3x.png
Labels: 🖼️ Design, 🍭 조이

#55 [FEAT] 온보딩 화면 구성
  Codingdong-iOS/Codingdong-iOS.xcodeproj/project.pbxproj
  Codingdong-iOS/Codingdong-iOS/Application/SceneDelegate.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Opening/ViewController/OnboardingViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Opening/ViewController/SplashViewController.swift
  Codingdong-iOS/Codingdong-iOS/Util/Manager/FontManager.swift
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Onboarding/Contents.json
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Onboarding/img_accessibility.imageset/Contents.json
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Onboarding/img_accessibility.imageset/Group 44253.png
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Onboarding/img_accessibility.imageset/Group 44253@2x.png
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Onboarding/img_accessibility.imageset/Group 44253@3x.png
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Onboarding/img_logo.imageset/BrightnessOption 1.png
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Onboarding/img_logo.imageset/BrightnessOption 1@2x.png
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Onboarding/img_logo.imageset/BrightnessOption 1@3x.png
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Onboarding/img_logo.imageset/Contents.json
Labels: ⭐️ Feat, 🍭 조이

#58 [Feat] 스토리 01 (해님달님) 인트로 뷰 추가, 전래동화 & 개념간식 더보기 뷰 추가
  Codingdong-iOS/Codingdong-iOS.xcodeproj/project.pbxproj
  Codingdong-iOS/Codingdong-iOS/Model/StoryTitle.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/MoreInfo/MoreBadge/ViewController/MoreBadgeViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/MoreInfo/MoreTitle/ViewController/MoreTItleViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/MyBookShelf/View/StoryListTableView.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/MyBookShelf/ViewController/MyBookShelfViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Opening/ViewController/SplashViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SunAndMoonIntro/View/SunAndMoonIntroView.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SunAndMoonIntro/ViewController/SunAndMoonIntroViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/TigerAnimation/VIewController/TigerAnimationViewController.swift
Labels: ⭐️ Feat, 🍺 션

#67 [FEAT] 개념 간식 더보기 뷰 추가
  Codingdong-iOS/Codingdong-iOS.xcodeproj/project.pbxproj
  Codingdong-iOS/Codingdong-iOS/Model/BadgeList.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/MoreInfo/MoreBadge/View/MoreBadgeCollectionView.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/MoreInfo/MoreBadge/View/MoreBadgeCollectionViewCell.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/MoreInfo/MoreBadge/ViewController/MoreBadgeViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/MyBookShelf/View/BadgeCollectionViewCell.swift
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Dummy/Contents.json
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Dummy/DummyA1.imageset/Contents.json
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Dummy/DummyA1.imageset/YugwaA1@2x.svg
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Dummy/DummyA2.imageset/Contents.json
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Dummy/DummyA2.imageset/YugwaA2@2x.svg
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Dummy/DummyA3.imageset/Contents.json
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Dummy/DummyA3.imageset/YugwaA3@2x.svg
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Dummy/DummyA4.imageset/Contents.json
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Dummy/DummyA4.imageset/YugwaA4@2x.svg
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Dummy/DummyB1.imageset/Contents.json
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Dummy/DummyB1.imageset/YugwaB1@2x.svg
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Dummy/DummyB2.imageset/Contents.json
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Dummy/DummyB2.imageset/YugwaB2@2x.svg
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Dummy/DummyB3.imageset/Contents.json
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Dummy/DummyB3.imageset/YugwaB3@2x.svg
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Dummy/DummyB4.imageset/Contents.json
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Dummy/DummyB4.imageset/YugwaB4@2x.svg
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Dummy/DummyB5.imageset/Contents.json
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Dummy/DummyB5.imageset/YugwaB5@2x.svg
Labels: ⭐️ Feat, 🍺 션

#71 [REFACTOR] 내 책장 뷰 리팩터링
  Codingdong-iOS/Codingdong-iOS.xcodeproj/project.pbxproj
  Codingdong-iOS/Codingdong-iOS/Model/Fable.swift
  Codingdong-iOS/Codingdong-iOS/Model/YugwaList.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Opening/View/BadgeCollectionViewCell.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Opening/View/StoryListTableView.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Opening/View/StoryListTableViewCell.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Opening/View/YugwaCell.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Opening/View/YugwaCollectionView.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Opening/ViewController/MyBookShelfViewController.swift
Labels: ♻️ Refactor, 🍭 조이

#72 [REFACTOR] 떡꼬치 화면 리팩토링
  Codingdong-iOS/Codingdong-iOS/Model/CodingBlock.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept1/View/TtekkkochiCollectionViewCell.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept1/View/TtekkkochiSelectionView.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept1/ViewController/TtekkkochiViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept1/ViewModel/TtekkkochiViewModel.swift
Labels: ♻️ Refactor, 🍭 조이

#75 [FEAT] OPENING 파트 화면 로직 수정
  Codingdong-iOS/Codingdong-iOS.xcodeproj/project.pbxproj
  Codingdong-iOS/Codingdong-iOS/Presentation/Opening/View/StoryListTableView.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Opening/ViewController/MyBookShelfViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Opening/ViewController/OnboardingViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Opening/ViewModel/MyBookShelfViewModel.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Opening/ViewModel/OnboardingViewModel.swift
Labels: ♻️ Refactor, 🍭 조이

#77 [REFACTOR] SM_Intro 관련 뷰 리팩터링
  Codingdong-iOS/Codingdong-iOS.xcodeproj/project.pbxproj
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept1/View/TigerEncountView.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept1/ViewController/TtekkkochiViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Intro/View/SunAndMoonIntroView.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Intro/ViewController/SunAndMoonIntroViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Intro/ViewController/TigerEncountViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Intro/ViewModel/SunAndMoonIntroViewModel.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Intro/ViewModel/TigerEncounterViewModel.swift
Labels: ♻️ Refactor, 🍭 조이

#80 [REFACTOR] 해님달님 - 호랑이 잡아먹는 애니메이션 뷰 수정
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept1/ViewController/TtekkkochiViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept2/ViewController/GiveTtekkViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept2/ViewController/IfConceptViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept2/ViewController/TigerAnimationViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Intro/ViewController/SunAndMoonIntroViewController.swift
Labels: ♻️ Refactor, 🍺 션

#82 [FEAT] 해님달님 엔딩 UI 구성
  Codingdong-iOS/Codingdong-iOS.xcodeproj/project.pbxproj
  Codingdong-iOS/Codingdong-iOS/Presentation/Components/Constants.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Ending/View/CustomCollectionViewFlowLayout.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Ending/View/ReviewCollectionViewCell.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Ending/ViewController/ReviewViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Ending/ViewModel/ReviewViewModel.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Intro/View/TigerEncountView.swift
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Learning Badge/Contents.json
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/The Sun and the Moon/sm_review1.imageset/Contents.json
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/The Sun and the Moon/sm_review1.imageset/concept3.png
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/The Sun and the Moon/sm_review1.imageset/concept3@2x.png
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/The Sun and the Moon/sm_review1.imageset/concept3@3x.png
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/The Sun and the Moon/sm_review2.imageset/Contents.json
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/The Sun and the Moon/sm_review2.imageset/concept4.png
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/The Sun and the Moon/sm_review2.imageset/concept4@2x.png
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/The Sun and the Moon/sm_review2.imageset/concept4@3x.png
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/The Sun and the Moon/sm_review3.imageset/Contents.json
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/The Sun and the Moon/sm_review3.imageset/concept5.png
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/The Sun and the Moon/sm_review3.imageset/concept5@2x.png
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/The Sun and the Moon/sm_review3.imageset/concept5@3x.png
Labels: ⭐️ Feat, 🍭 조이

#76 [FEAT] 창문 스토리 뷰
  Codingdong-iOS/Codingdong-iOS.xcodeproj/project.pbxproj
  Codingdong-iOS/Codingdong-iOS/Presentation/Window/View/TigerHandHoleAnimationView.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Window/View/TigerNoseHoleAnimationView.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Window/View/TigerTailHoleAnimationView.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Window/ViewController/AndConceptViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Window/ViewController/WindowEndingViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Window/ViewController/WindowHoleViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Window/ViewController/WindowStartViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Window/ViewController/WindowVoiceChildViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Window/ViewController/WindowVoiceViewController.swift
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/doorWithHoles.imageset/Contents.json
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/doorWithHoles.imageset/doorWithHoles.png
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/doorWithHoles.imageset/doorWithHoles@2x.png
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/doorWithHoles.imageset/doorWithHoles@3x.png
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/initialDoor.imageset/Contents.json
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/initialDoor.imageset/Door.png
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/initialDoor.imageset/Door@2x.png
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/initialDoor.imageset/Door@3x.png
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/tigerEatEnding.imageset/Contents.json
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/tigerEatEnding.imageset/tigerEatEnding.png
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/tigerEatEnding.imageset/tigerEatEnding@2x.png
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/tigerEatEnding.imageset/tigerEatEnding@3x.png
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/tiger_concept.imageset/Contents.json
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/tiger_concept.imageset/tiger.png
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/tiger_concept.imageset/tiger@2x.png
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/tiger_concept.imageset/tiger@3x.png
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Lottie/TigerHandHoleAnimation.json
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Lottie/TigerNoseHoleAnimation.json
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Lottie/TigerTailHoleAnimation.json
Labels: ⭐️ Feat, 🚢 노아

#87 [FEAT] STT 기능 구현
  Codingdong-iOS/Codingdong-iOS.xcodeproj/project.pbxproj
  Codingdong-iOS/Codingdong-iOS/Presentation/Opening/ViewController/OnboardingViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Window/ViewController/WindowVoiceChildViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Window/ViewController/WindowVoiceViewController.swift
  Codingdong-iOS/Codingdong-iOS/Util/Manager/PermissionManager.swift
Labels: ⭐️ Feat, 🚢 노아

#89 [FEAT] 권한거부 및 뷰 전환 코드 추가
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept2/ViewController/WindowEndingViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept2/ViewController/WindowVoiceChildViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept2/ViewController/WindowVoiceViewController.swift
  Codingdong-iOS/Codingdong-iOS/Util/Manager/PermissionManager.swift
Labels: ⭐️ Feat, 🚢 노아

#92 [REFACTOR] 떡 주기 화면 리팩토링 및 접근성 적용
  Codingdong-iOS/Codingdong-iOS.xcodeproj/project.pbxproj
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept1/View/TigerLottieAnimationVIew.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept1/ViewController/GiveTtekkViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept1/ViewController/TigerAnimationViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept2/View/TigerHandHoleAnimationView.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept2/View/TigerNoseHoleAnimationView.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept2/View/TigerTailHoleAnimationView.swift
  Codingdong-iOS/Codingdong-iOS/Util/Manager/LottieManager.swift
Labels: ♻️ Refactor, 🍺 션

#93 [REFACTOR] SM_Concept2 보이스오버 및 네비게이션 링크 연결
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept2/ViewController/AndConceptViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept2/ViewController/WindowEndingViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept2/ViewController/WindowHoleViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept2/ViewController/WindowStartViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept2/ViewController/WindowVoiceChildViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept2/ViewController/WindowVoiceViewController.swift
Labels: ♻️ Refactor, 🚢 노아

#95 [REFACTOR] 떡주기 뷰 업데이트된 라벨 정보 전달
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept1/ViewController/GiveTtekkViewController.swift
Labels: ♻️ Refactor, 🍺 션

#96 [FEAT] 창문 로띠뷰에서 음성인식 뷰로 넘어가는 기능
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept2/ViewController/WindowHoleViewController.swift
Labels: ⭐️ Feat, 🚢 노아

#101 [FEAT] 반복문 UI 화면 전환
  Codingdong-iOS/Codingdong-iOS.xcodeproj/project.pbxproj
  Codingdong-iOS/Codingdong-iOS/Application/SceneDelegate.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept2/ViewController/WindowStartViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept3/ViewController/TeachingRepeatViewController.swift
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/The Sun and the Moon/Ttek.imageset/Contents.json
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/The Sun and the Moon/Ttek.imageset/Rectangle 4489.png
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/The Sun and the Moon/Ttek.imageset/Rectangle 4489@2x.png
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/The Sun and the Moon/Ttek.imageset/Rectangle 4489@3x.png
Labels: ⭐️ Feat, 🍭 조이

#102 [FEAT] Accessibility 추가
  Codingdong-iOS/Codingdong-iOS.xcodeproj/project.pbxproj
  Codingdong-iOS/Codingdong-iOS/Application/SceneDelegate.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Opening/ViewController/OnboardingViewController.swift
Labels: ⭐️ Feat, 🍭 조이

#103 [FEAT] 보이스 오버 기능 체크
  Codingdong-iOS/Codingdong-iOS.xcodeproj/project.pbxproj
  Codingdong-iOS/Codingdong-iOS/Presentation/Opening/View/StoryListTableView.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Opening/ViewController/MyBookShelfViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept1/ViewController/GiveTtekkViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept1/ViewController/IfConceptViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept1/ViewController/TigerAnimationViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept1/ViewController/TtekkkochiViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept2/ViewController/AndConceptViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept3/ViewController/OnuiiViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept3/ViewController/RepeatConceptViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept3/ViewController/SunMoonOnuiiViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept3/ViewController/TeachingRepeatViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Ending/ViewController/ReviewViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Ending/ViewModel/ReviewViewModel.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Intro/ViewController/SunAndMoonIntroViewController.swift
Labels: ⭐️ Feat, 🍭 조이

#100 [FIX] STT 뷰, 떡 주기 뷰 보이스오버 픽스
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept1/ViewController/GiveTtekkViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept2/ViewController/WindowVoiceChildViewController.swift
Labels: 🐛 Fix, 🍺 션

#107 [FIX] 앱 전체에서 햅틱 반응 있던 현상 수정
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept1/ViewController/GiveTtekkViewController.swift
Labels: 🐛 Fix, 🚢 노아

#104 [FEAT] 보이스오버 기능 체크
  Codingdong-iOS/Codingdong-iOS.xcodeproj/project.pbxproj
  Codingdong-iOS/Codingdong-iOS/Presentation/Opening/ViewController/MyBookShelfViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept1/ViewController/TtekkkochiViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Ending/ViewController/ReviewViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Intro/View/SunAndMoonIntroView.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Intro/ViewController/SunAndMoonIntroViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Intro/ViewController/TigerEncountViewController.swift
Labels: ♻️ Refactor, 🍭 조이

#105 [Fix] 남매 집에 도착한 호랑이 관련 에러 해결
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept1/ViewController/IfConceptViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept2/ViewController/WindowEndingViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept2/ViewController/WindowStartViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept2/ViewController/WindowVoiceChildViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept2/ViewController/WindowVoiceViewController.swift
Labels: 🐛 Fix, 🍭 조이

#110 [Fix] 각종 버그 수정
  Codingdong-iOS/Codingdong-iOS/Presentation/Components/CardView.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Opening/View/YugwaCell.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Opening/ViewController/MyBookShelfViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept1/ViewController/GiveTtekkViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept1/ViewController/IfConceptViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept1/ViewController/TigerAnimationViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept2/ViewController/AndConceptViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept2/ViewController/WindowEndingViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept2/ViewController/WindowHoleViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept2/ViewController/WindowStartViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept2/ViewController/WindowVoiceChildViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept2/ViewController/WindowVoiceViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept3/ViewController/OnuiiViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept3/ViewController/RopeViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept3/ViewController/SunMoonOnuiiViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept3/ViewController/TeachingRepeatViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Ending/ViewController/ReviewViewController.swift
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/The Sun and the Moon/sm_bgView.imageset/Contents.json
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/The Sun and the Moon/sm_bgView.imageset/Story_01_Quiz2_Voice.png
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/The Sun and the Moon/sm_bgView.imageset/Story_01_Quiz2_Voice@2x.png
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/The Sun and the Moon/sm_bgView.imageset/Story_01_Quiz2_Voice@3x.png
Labels: 🐛 Fix, 🍭 조이

#113 [FEAT] 반복문 블럭에 애니메이션 적용, 사소한 버그 수정
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept1/ViewController/TigerAnimationViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept2/ViewController/WindowVoiceChildViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept3/ViewController/RepeatConceptViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept3/ViewController/TeachingRepeatViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Ending/ViewController/ReviewViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Intro/ViewController/TigerEncountViewController.swift
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/The Sun and the Moon/sm_repeat3.imageset/Contents.json
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/The Sun and the Moon/sm_repeat3.imageset/sm_repeat3.svg
Labels: 🐛 Fix, ⭐️ Feat, 🍺 션

#115 [FEAT] 내 책장 버튼 누르면 앱 종료되는 이슈 해결
  Codingdong-iOS/Codingdong-iOS/Presentation/Opening/ViewController/OnboardingViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept1/ViewController/GiveTtekkViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept1/ViewController/TigerAnimationViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept1/ViewController/TtekkkochiViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept2/ViewController/WindowEndingViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept2/ViewController/WindowVoiceChildViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept3/ViewController/TeachingRepeatViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Intro/ViewController/SunAndMoonIntroViewController.swift
Labels: 🐛 Fix, 🍺 션

#119 [Setting] 콩쥐팥쥐 폴더링
  Codingdong-iOS/Codingdong-iOS.xcodeproj/project.pbxproj
  Codingdong-iOS/Codingdong-iOS/Presentation/KZ_Concept1/ViewController/HouseWorkStartViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/KZ_Concept2/ViewController/WorkingKongZwiStartViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/KZ_Concept3/ViewController/KkotSinOwnerStartViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/KZ_Ending/ViewController/KzPzReviewViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/KZ_Intro/ViewController/KzPzIntroViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept1/ViewController/TigerAnimationViewController.swift
Labels: ⚙️ Setting, 🍺 션

#121 #120 qa fix
  Codingdong-iOS/Codingdong-iOS.xcodeproj/project.pbxproj
  Codingdong-iOS/Codingdong-iOS/Application/SceneDelegate.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Opening/View/StoryListTableViewCell.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Opening/View/YugwaCell.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept1/ViewController/GiveTtekkViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept1/ViewController/IfConceptViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept1/ViewController/TigerAnimationViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept1/ViewController/TtekkkochiViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept2/ViewController/AndConceptViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept2/ViewController/WindowEndingViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept2/ViewController/WindowHoleViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept2/ViewController/WindowStartViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept2/ViewController/WindowVoiceChildViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept3/ViewController/OnuiiViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept3/ViewController/RepeatConceptViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept3/ViewController/RopeViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept3/ViewController/SunMoonOnuiiViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept3/ViewController/TeachingRepeatViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Ending/ViewController/ReviewViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Intro/ViewController/SunAndMoonIntroViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Intro/ViewController/TigerEncountViewController.swift
  Codingdong-iOS/Codingdong-iOS/Util/Manager/LottieManager.swift
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Lottie/OnuiAnimation.json
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Lottie/OnuiAnimation_Fixed.json
Labels: 🐛 Fix, 🍺 션

#122 [SETTING] 앱스토어 리젝 대비용
  Codingdong-iOS/Codingdong-iOS.xcodeproj/project.pbxproj
  Codingdong-iOS/Codingdong-iOS/Application/SceneDelegate.swift
  Codingdong-iOS/Codingdong-iOS/Model/Fable.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Opening/View/StoryListTableView.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Opening/ViewController/MyBookShelfViewController.swift
  README.md
  screenshot.png
Labels: ⚙️ Setting

#125 [Feat] SM-Intro 그룹핑 개선
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Intro/ViewController/SunAndMoonIntroViewController.swift
Labels: ⭐️ Feat, 🍺 션

#128 [FEAT] 전래 동화 모델에 SwiftData 적용
  Codingdong-iOS/Codingdong-iOS.xcodeproj/project.pbxproj
  Codingdong-iOS/Codingdong-iOS/Data/FableDBService.swift
  Codingdong-iOS/Codingdong-iOS/Model/Fable.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Opening/View/StoryListTableView.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Opening/View/StoryListTableViewCell.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Opening/ViewController/MyBookShelfViewController.swift
Labels: ⭐️ Feat, 🍭 조이

#129 [FEAT] 보이스오버 기능 개선
  Codingdong-iOS/Codingdong-iOS.xcodeproj/project.pbxproj
  Codingdong-iOS/Codingdong-iOS/Model/CodingBlock.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Components/CardView.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Opening/ViewController/MyBookShelfViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept1/ViewController/GiveTtekkViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept1/ViewController/IfConceptViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept1/ViewController/TigerAnimationViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept1/ViewController/TtekkkochiViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept2/ViewController/WindowEndingViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept2/ViewController/WindowHoleViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept2/ViewController/WindowVoiceChildViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept3/ViewController/SunMoonOnuiiViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept3/ViewController/TeachingRepeatViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Intro/ViewController/SunAndMoonIntroViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Intro/ViewController/TigerEncountViewController.swift
  Codingdong-iOS/Codingdong-iOS/Util/Extension/UIViewController+.swift
Labels: ⭐️ Feat, 🍺 션

#130 [Fix] 전래동화 목록 Sort 하기
  Codingdong-iOS/Codingdong-iOS.xcodeproj/project.pbxproj
  Codingdong-iOS/Codingdong-iOS/Data/FableDBService.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Opening/ViewController/MyBookShelfViewController.swift
Labels: 🐛 Fix, 🍭 조이

#131 [FEAT] 챕터 2, 챕터 3, 복습 파트 보이스 오버 기능 개선
  Codingdong-iOS/Codingdong-iOS/Presentation/Components/CardView.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Opening/ViewController/OnboardingViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept1/ViewController/GiveTtekkViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept1/ViewController/IfConceptViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept1/ViewController/TigerAnimationViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept1/ViewController/TtekkkochiViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept2/View/TigerHandHoleAnimationView.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept2/View/TigerNoseHoleAnimationView.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept2/View/TigerTailHoleAnimationView.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept2/ViewController/AndConceptViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept2/ViewController/WindowEndingViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept2/ViewController/WindowHoleViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept2/ViewController/WindowStartViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept2/ViewController/WindowVoiceViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept3/ViewController/OnuiiViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept3/ViewController/RepeatConceptViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept3/ViewController/RopeViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept3/ViewController/SunMoonOnuiiViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept3/ViewController/TeachingRepeatViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Ending/ViewController/ReviewViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Intro/ViewController/SunAndMoonIntroViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Intro/ViewController/TigerEncountViewController.swift
Labels: ⭐️ Feat

#134 [FEAT] 개념 간식 모음에 SwiftData 적용
  Codingdong-iOS/Codingdong-iOS.xcodeproj/project.pbxproj
  Codingdong-iOS/Codingdong-iOS/Data/CodingdongDBService.swift
  Codingdong-iOS/Codingdong-iOS/Model/BadgeList.swift
  Codingdong-iOS/Codingdong-iOS/Model/Fable.swift
  Codingdong-iOS/Codingdong-iOS/Model/Food.swift
  Codingdong-iOS/Codingdong-iOS/Model/StoryTitle.swift
  Codingdong-iOS/Codingdong-iOS/Model/YugwaList.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/KZ_Concept1/ViewController/HouseWorkStartViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/KZ_Concept2/ViewController/WorkingKongZwiStartViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/KZ_Concept3/ViewController/KkotSinOwnerStartViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/KZ_Ending/ViewController/KzPzReviewViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/KZ_Intro/ViewController/KzPzIntroViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Opening/View/MoreBadgeCollectionView.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Opening/View/MoreBadgeCollectionViewCell.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Opening/View/StoryListTableView.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Opening/View/YugwaCell.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Opening/View/YugwaCollectionView.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Opening/ViewController/MoreBadgeViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Opening/ViewController/MoreTitleViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Opening/ViewController/MyBookShelfViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept1/ViewController/IfConceptViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Ending/ViewModel/ReviewViewModel.swift
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Dummy/Contents.json
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Dummy/DummyA1.imageset/Contents.json
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Dummy/DummyA1.imageset/YugwaA1@2x.svg
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Dummy/DummyA2.imageset/Contents.json
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Dummy/DummyA2.imageset/YugwaA2@2x.svg
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Dummy/DummyA3.imageset/Contents.json
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Dummy/DummyA3.imageset/YugwaA3@2x.svg
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Dummy/DummyA4.imageset/Contents.json
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Dummy/DummyA4.imageset/YugwaA4@2x.svg
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Dummy/DummyB1.imageset/Contents.json
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Dummy/DummyB1.imageset/YugwaB1@2x.svg
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Dummy/DummyB2.imageset/Contents.json
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Dummy/DummyB2.imageset/YugwaB2@2x.svg
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Dummy/DummyB3.imageset/Contents.json
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Dummy/DummyB3.imageset/YugwaB3@2x.svg
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Dummy/DummyB4.imageset/Contents.json
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Dummy/DummyB4.imageset/YugwaB4@2x.svg
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Dummy/DummyB5.imageset/Contents.json
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Dummy/DummyB5.imageset/YugwaB5@2x.svg
Labels: ⭐️ Feat, 🍭 조이

#135 [FEAT] 코딩동 DBService 업데이트
  Codingdong-iOS/Codingdong-iOS/Application/SceneDelegate.swift
  Codingdong-iOS/Codingdong-iOS/Data/CodingdongDBService.swift
  Codingdong-iOS/Codingdong-iOS/Model/Food.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Opening/View/StoryListTableView.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Opening/View/YugwaCell.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Opening/View/YugwaCollectionView.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Opening/ViewController/MyBookShelfViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept1/View/TtekkkochiSelectionView.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept1/ViewController/IfConceptViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Intro/ViewModel/SunAndMoonIntroViewModel.swift
Labels: ♻️ Refactor, ⭐️ Feat, 🍭 조이

#137 [FEAT] 커스텀 얼럿 구현
  Codingdong-iOS/Codingdong-iOS.xcodeproj/project.pbxproj
  Codingdong-iOS/Codingdong-iOS/Presentation/CumstomAlert/ViewController/CustomAlert.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept1/ViewController/GiveTtekkViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept1/ViewController/IfConceptViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept1/ViewController/TigerAnimationViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept1/ViewController/TtekkkochiViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept2/ViewController/AndConceptViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept2/ViewController/WindowEndingViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept2/ViewController/WindowHoleViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept2/ViewController/WindowStartViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept2/ViewController/WindowVoiceViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept3/ViewController/OnuiiViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept3/ViewController/RepeatConceptViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept3/ViewController/RopeViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept3/ViewController/SunMoonOnuiiViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept3/ViewController/TeachingRepeatViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Ending/ViewController/ReviewViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Intro/ViewController/SunAndMoonIntroViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Intro/ViewController/TigerEncountViewController.swift
Labels: ⭐️ Feat, 🍺 션

#138 [FEAT] 해님달님 개념 2와 3에 swiftdata 적용
  Codingdong-iOS/Codingdong-iOS.xcodeproj/project.pbxproj
  Codingdong-iOS/Codingdong-iOS/Data/CddDBService.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/CumstomAlert/ViewController/CustomAlert.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Opening/ViewController/MyBookShelfViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept1/ViewController/IfConceptViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept2/ViewController/AndConceptViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Concept3/ViewController/SunMoonOnuiiViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Intro/ViewController/TigerEncountViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/SM_Intro/ViewModel/SunAndMoonIntroViewModel.swift
Labels: ⭐️ Feat, 🍭 조이

#144 [REFACTOR] 떡꼬치 화면 Refactoring
  Codingdong-iOS/Codingdong-iOS/Model/CodingBlock.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Components/BasePaddingLabel.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/The Sun and the moon/SM_Concept1/View/TtekkkochiCollectionViewCell.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/The Sun and the moon/SM_Concept1/View/TtekkkochiSelectionView.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/The Sun and the moon/SM_Concept1/ViewController/TtekkkochiViewController.swift
Labels: ♻️ Refactor, ⭐️ Feat, 🍭 조이

#145 [REFACTOR] 개념 간식 모음 리팩터링
  Codingdong-iOS/Codingdong-iOS/Presentation/Opening/View/YugwaCell.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Opening/View/YugwaCollectionView.swift
Labels: ♻️ Refactor, 🍭 조이
