Repository DeveloperAcademy-POSTECH/MacC-Team5-COMBINE, pull requests merged in 2023-10, with the labels that each got.

#3 [SETTING] 프로젝트 설계
  Codingdong-iOS/.swiftlint.yml
  Codingdong-iOS/Codingdong-iOS.xcodeproj/project.pbxproj
  Codingdong-iOS/Codingdong-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Codingdong-iOS/Codingdong-iOS/Application/AppDelegate.swift
  Codingdong-iOS/Codingdong-iOS/Application/SceneDelegate.swift
  Codingdong-iOS/Codingdong-iOS/Base.lproj/Main.storyboard
  Codingdong-iOS/Codingdong-iOS/Presentation/ViewController.swift
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/Contents.json
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Base.lproj/LaunchScreen.storyboard
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Info.plist
Labels: ⚙️ Setting, 🍭 조이

#6 [SETTING] #5-FontManager 추가
  Codingdong-iOS/Codingdong-iOS.xcodeproj/project.pbxproj
  Codingdong-iOS/Codingdong-iOS/Util/Manager/FontManager.swift
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Font/Pretendard-Black.otf
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Font/Pretendard-Bold.otf
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Font/Pretendard-ExtraBold.otf
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Font/Pretendard-ExtraLight.otf
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Font/Pretendard-Light.otf
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Font/Pretendard-Medium.otf
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Font/Pretendard-Regular.otf
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Font/Pretendard-SemiBold.otf
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Font/Pretendard-Thin.otf
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Info.plist
Labels: ⚙️ Setting, 🍺 션

#11 [DESIGN] 공용 디자인 요소 설정
  Codingdong-iOS/Codingdong-iOS.xcodeproj/project.pbxproj
  Codingdong-iOS/Codingdong-iOS/Presentation/Common/CommonButton.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Common/ConfigUI.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Common/Constants.swift
Labels: 🖼️ Design, 🍭 조이

#13 [Fix] Swift API guideline에 따라 색상 코드 변수명 수정
  Codingdong-iOS/Codingdong-iOS/Util/Colors/UIColorExtension.swift
Labels: 🐛 Fix, 🍭 조이

#15 [Setting] 번들 identifier 변경
  Codingdong-iOS/Codingdong-iOS.xcodeproj/project.pbxproj
Labels: ⚙️ Setting, 🍭 조이

#18 [FEAT] 떡꼬치 UI 구성
  Codingdong-iOS/Codingdong-iOS.xcodeproj/project.pbxproj
  Codingdong-iOS/Codingdong-iOS/Model/CodingBlock.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Components/BasePaddingLabel.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Components/CommonButton.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Components/ConfigUI.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Components/Constants.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Ttekkkochi/View/TtekkkochiCollectionViewCell.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Ttekkkochi/View/TtekkkochiSelectionView.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Ttekkkochi/ViewController/TtekkkochiViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Ttekkkochi/ViewModel/TtekkkochiViewModel.swift
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Info.plist
  Codingdong-iOS/Codingdong-iOS/Util/Resources/ko.lproj/LaunchScreen.strings
Labels: ⭐️ Feat, 🍭 조이

#25 [Feat] 떡꼬치 UI 구현
  Codingdong-iOS/Codingdong-iOS.xcodeproj/project.pbxproj
  Codingdong-iOS/Codingdong-iOS/Presentation/Ttekkkochi/View/TtekkkochiCollectionViewCell.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Ttekkkochi/View/TtekkkochiSelectionView.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Ttekkkochi/ViewController/TtekkkochiViewController.swift
  Codingdong-iOS/Codingdong-iOS/Util/Manager/SoundManager.swift
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Logger.swift
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Sound/bell.mp3
Labels: ⭐️ Feat, 🍭 조이

#24 [Refactor] Font Design Guide 반영
  Codingdong-iOS/Codingdong-iOS/Util/Manager/FontManager.swift
Labels: ♻️ Refactor, 🍺 션

#29 [FEAT] 흔드는 횟수 카운트 구현
  Codingdong-iOS/Codingdong-iOS.xcodeproj/project.pbxproj
  Codingdong-iOS/Codingdong-iOS/Presentation/Quiz1/Quiz1ViewController.swift
Labels: ⭐️ Feat, 🚢 노아

#31 [FEAT] Ttekk interaction 구현
  Codingdong-iOS/Codingdong-iOS.xcodeproj/project.pbxproj
  Codingdong-iOS/Codingdong-iOS/Presentation/GiveTtekk/GiveTtekkViewController.swift
Labels: ⭐️ Feat, 🚢 노아

#30 [FEAT] #22 LottieManager 구현
  Codingdong-iOS/Codingdong-iOS.xcodeproj/project.pbxproj
  Codingdong-iOS/Codingdong-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Codingdong-iOS/Codingdong-iOS/Presentation/TigerAnimation/VIewController/TigerAnimationViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/TigerAnimation/View/TigerLottieAnimationVIew.swift
  Codingdong-iOS/Codingdong-iOS/Util/Manager/HapticManager.swift
  Codingdong-iOS/Codingdong-iOS/Util/Manager/LottieManager.swift
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Lottie/TigerAnimation.json
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Lottie/TigerAnimation_HD.json
Labels: ⭐️ Feat, 🍺 션

#33 [FEAT] #32 떡 주기 UI 구현
  Codingdong-iOS/Codingdong-iOS.xcodeproj/project.pbxproj
  Codingdong-iOS/Codingdong-iOS/Presentation/GiveTtekk/GiveTtekkViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/GiveTtekk/NoTtekkViewController.swift
Labels: ⭐️ Feat, 🚢 노아

#35 [Feat] #34 label 줄바꿈 처리
  Codingdong-iOS/Codingdong-iOS/Presentation/TigerAnimation/VIewController/TigerAnimationViewController.swift
Labels: ⭐️ Feat, 🍺 션

#36 [DESIGN] 네비게이션 바 만들기
  Codingdong-iOS/Codingdong-iOS.xcodeproj/project.pbxproj
  Codingdong-iOS/Codingdong-iOS/Presentation/Components/CommonButton.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Components/ConfigUI.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/TigerAnimation/VIewController/TigerAnimationViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Ttekkkochi/ViewController/TtekkkochiViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Ttekkkochi/ViewModel/TtekkkochiViewModel.swift
  Codingdong-iOS/Codingdong-iOS/Util/Colors/UIColor+.swift
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/AppIcon.appiconset/AppIcon.png
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Codingdong-iOS/Codingdong-iOS/Util/Resources/Log.swift
Labels: 🖼️ Design, 🍭 조이

#37 [FEAT] 네비게이션 기능 구현
  Codingdong-iOS/Codingdong-iOS.xcodeproj/project.pbxproj
  Codingdong-iOS/Codingdong-iOS/Presentation/GiveTtekk/GiveTtekkViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/GiveTtekk/NoTtekkViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/TigerAnimation/VIewController/TigerAnimationViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Ttekkkochi/ViewController/TtekkkochiViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/ViewController.swift
Labels: ⭐️ Feat, 🍭 조이

#38 [FEAT] 보이스오버 기능 체크
  Codingdong-iOS/Codingdong-iOS/Presentation/Components/BasePaddingLabel.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Components/ConfigUI.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/GiveTtekk/GiveTtekkViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/GiveTtekk/NoTtekkViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/TigerAnimation/VIewController/TigerAnimationViewController.swift
  Codingdong-iOS/Codingdong-iOS/Presentation/Ttekkkochi/ViewController/TtekkkochiViewController.swift
Labels: ⭐️ Feat, 🍭 조이
